FLASK_APP=backend.py

DATABASE_DEV_URI=""
CASSANDRA_HOSTS_DEV=['127.0.0.1']
CASSANDRA_KEYSPACE_DEV=DataStax
CSQLALCHEMY_DATABASE_DEV_URI=""
AWS_KEY_ID_DEV=""
AWS_ACCESS_KEY_DEV=""

DATABASE_PROD_URI=""
CASSANDRA_HOSTS_PROD=['']
CASSANDRA_KEYSPACE_PROD=DataStax
CSQLALCHEMY_DATABASE_PROD_URI=""
AWS_KEY_ID_PROD=""
AWS_ACCESS_KEY_PROD=""
